services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  gestures-service:
    container_name: gestures-service
    build: .
    env_file:
      - .env
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    depends_on:
      - postgres

volumes:
  pg_data:
