app:
  name: sso-service
  env: development
  grpc:
    timeout: 1m
    port: 3000 
  jwt_secret_key: "cyansnbrst"
  jwt_token_ttl: 1h

postgres:                     
  max_pool_size: 50
  conn_timeout: 10s
  driver: pgx