services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  sso-service:
    container_name: sso-service
    build: .
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - postgres

volumes:
  pg_data:
